
version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7.24
    ports:
    - "13306:3306"
    environment:
      MYSQL_DATABASE: "keycloak"
      MYSQL_USER: "keycloak"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:4.8.1.Final
    command: ["-b", "0.0.0.0",  "--debug 8787", "-Djboss.socket.binding.port-offset=100", "-Djboss.bind.address.management=0.0.0.0"]
    ports:
    - "8787:8787" # debug port
    - "8180:8180" # keycloak server
    - "10090:10090" # wilfly management console
    depends_on:
    - mysql
    volumes:
    - ./themes/custom:/opt/jboss/keycloak/themes/custom
    environment:
      DB_VENDOR: "mysql"
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      MYSQL_USERNAME: keycloak
      MYSQL_PASSWORD: password
  maildev:
    container_name: maildev
    image: djfarrelly/maildev
    ports:
    - "8081:80"
